#配置选择配置文件
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML5
  mvc:
    favicon:
      enabled: false



